services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ApiInsight\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,Tests}'

    ApiInsight\EventListener\ApiRequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10 }
            - { name: kernel.event_listener, event: kernel.response, priority: -10 }
            - { name: kernel.event_listener, event: kernel.exception, priority: 0 }

    ApiInsight\Service\MetricsStorageInterface:
        factory: ['ApiInsight\Service\MetricsStorageFactory', 'create']
        arguments:
            $storageType: '%api_insight.storage%'

    ApiInsight\Controller\MetricsController:
        arguments:
            $authEnabled: '%api_insight.auth_enabled%'
            $authType: '%api_insight.auth_type%'
            $authToken: '%api_insight.auth_token%'
            $prometheusEnabled: '%api_insight.prometheus_enabled%'
        tags: ['controller.service_arguments'] 